### PR TITLE
Add header animation

### PR DESCRIPTION
**Pull request by sigvef**
Implemented with css animations and translate3d, so hopefully it won't be a resource hog.

### CODE REVIEW

**Comment by stianjensen** [comment]
needs rebase

**Comment by sigvef** [comment]
ping, (also, fully blue background looked nicer imo)

**Comment by stianjensen** [comment]
> also, fully blue background looked nicer imo)

You mean you liked it better without the stars?

**Comment by sigvef** [comment]
No, like this:

image

no white body bg.

**Comment by cristeahub** [comment]
Not sure about the effect to be honest, I'm not a fan of those things on web pages. What do you other guys think?

Bigger image of what it looks like now:

image

**Comment by stianjensen** [comment]
I think you makes sense for this kind of website to have some effects that wouldn't necessarily fit on all other sites, us being a democrew. This specific effect I will have a look at when I have proper internet for my laptop.

**Comment by cristeahub** [comment]
> I think you makes sense for this kind of website to have some effects that wouldn't necessarily fit on all other sites, us being a democrew. This specific effect I will have a look at when I have proper internet for my laptop.

I agree on that. I'll let you sit down with the effect and let you decide.

**Comment by stianjensen** [comment]
I think this looks cool! 😎

**Pull request merged**
