### PR TITLE
Add stubs for a bunch of posts

### PR DESCRIPTION
**Pull request by sigvef**

### CODE REVIEW

**Comment by cristeahub** [comment]
I think we should talk about what information to include in each post. I was thinking only a link to pouet might be better? So we don't have to duplicate all the links already present here.

**Comment by stianjensen** [comment]
I think more links on our site is nice, because then you save the extra step of going through pouet to find what you're looking for.

Based on feedback when posting on reddit etc. people unfamiliar with pouet have even commented they couldn't find youtube links there etc

**Comment by stianjensen** [comment]
needs rebase

**Comment by sigvef** [comment]
I agree with Stian (though the links could do with more styling, as an aside).

**Comment by sigvef** [comment]
rebased

**Pull request merged**
